export const DEFAULT_LAYOUT = "default";

export const POST_TYPE = {
  HOME_POST: "Home Post",
  PROFILE_POST: "Profile Post",
  SINGLE_POST: "Single Post",
  GROUP_POST: "Group Post",
  GROUP_FEED: "Group feed post",
};

export const FRIEND_TYPE = {
  ALL: 0,
  PENDING_ME: 1,
  PENDING_OTHER: 2,
  ACCEPTED: 3,
  BLOCKED: 4,
  REFUSED: 5,
  SELF: 6,
  NOT_FRIEND: 7,
  SUGGESTION: 8,
};

export const FRIENDSHIP_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  BLOCKED: 3,
  NOT_FRIEND: 4,
  SELF: 5,
};

export const POST_EDITOR_TYPE = {
  CREATE: 1,
  UPDATE: 2,
  SHARE: 3,
};

export const NOTIFICATION_TYPE = {
  POST_REACTION: "POST_REACTION",
  POST_COMMENT: "POST_COMMENT",
  CREATE_POST: "CREATE_POST",
  FRIEND_REQUEST: "FRIEND_REQUEST",
  SHARE_POST: "SHARE_POST",
  COMMENT_REACTION: "COMMENT_REACTION",
};

export const GROUP_TYPE = {
  ALL: 0,
  JOINED_GROUP: 1,
  MANAGE_BY_ME: 2,
  BOTH_JOINED_MANAGED: 3,
};

export const MEMBER_TYPE = {
  ALL: 0,
  ADMIN_ONLY: 1,
  SUPER_ADMIN: 2,
  NORMAL: 3,
};
