name: CICD_Docker

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker build . -t duonga6/facebook-clone
          docker run -d -p 8080:80 -p 8081:443 --name facebook-clone duonga6/facebook-clone

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/facebook-clone

      - name: Test container
        run: |
          docker ps -a
          
  update_server:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop facebook-clone
            docker container prune -f
            docker image pull duonga6/facebook-clone
            docker run -d -p 8080:80 -p 8081:443 --name facebook-clone duonga6/facebook-clone
            docker image prune -f
            ufw-docker allow facebook-clone
